### ISSUE TITLE
SCSS vs CSS 

### ISSUE THREAD

**Issue by wilkosz** [saldanan1/DocHubs-App#5]
## Issues 
Finding it difficult to use CSS to style elements and sub-elements?

>SCSS is a special type of file for SASS, a program written in Ruby that assembles CSS style sheets for a browser. SCSS is like CSS with better formatting. Being an extension of CSS3, in SCSS, we can add nested rules, variables, mixins, selector inheritance, and more.

## Fix 
1. https://create-react-app.dev/docs/adding-a-sass-stylesheet/  
2. Change HTML to include one global CSS Selector for each route/component 

```HTML
<section className = "Welcome-text">
                <h1><strong>Hey, I'm Noah Saldaña</strong></h1>
                <section className = "Welcome-sub">
                  <p>iOS Developer - Student Mentor - Human-Centered Designer</p>
                </section>
                <section className = "Nav">
                  <ul id="nav">
                    <Link to="/">Home</Link>
                    <Link to="/projects">Projects</Link>
                    <Link to="/aboutme">About Me</Link>
                  </ul>
                </section>
              </section>
```
cleans up to 

```HTML
<div class="header">
                  <h1><strong>Hey, I'm Noah Saldaña</strong></h1>
                  <p>iOS Developer - Student Mentor - Human-Centered Designer</p>
                  <ul>
                    <Link to="/">Home</Link>
                    <Link to="/projects">Projects</Link>
                    <Link to="/aboutme">About Me</Link>
                  </ul>
                </div>
```

with `App.scss`

```SCSS
body{
  background-color:#FFFAFA;;
}
.header {
  text-align: center;
  margin: auto;
  width: 50%;
  padding-top: 5%;
  font-family: sans-serif;
  h1 {
    font-size: calc(10px + 2vmin);
  }
  ul {
    width: 100%;
    margin: 0 0 3em 0;
    padding: 0;
    list-style: none;
    background-color: #e8f1f5;
    border-bottom: 1px solid #ccc;
    border-top: 1px solid #ccc;
    a {
      padding: 1px 15px;
      text-decoration: none;
      font-weight: bold;
      color: #069;
      border-right: 1px solid #ccc;
    }
    &:hover {
      color: black;
    }
  }
}
```
